//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP1TP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteGrado
    {
        public int ID { get; set; }
        public string Anho { get; set; }
        public Nullable<int> Estudiante_Id { get; set; }
        public Nullable<int> Carrera_Id { get; set; }
        public Nullable<int> Curso_Id { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
