//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP1TP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int Persona_Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public Nullable<int> Ciudad_Id { get; set; }
        public Nullable<int> Pais_Id { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiante> Estudiante { get; set; }
    }
}
