//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalEnunciadoD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion_Salarial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuracion_Salarial()
        {
            this.Empleado_Honorario = new HashSet<Empleado_Honorario>();
        }
    
        public int Configuracion_Salarial_Id { get; set; }
        public Nullable<decimal> Configuracion_Salarial_Importe_Neto { get; set; }
        public Nullable<decimal> Configuracion_Salarial_Importe_Descuento { get; set; }
        public Nullable<decimal> Configuracion_Salarial_Jornal_Diario { get; set; }
        public Nullable<decimal> Configuracion_Salarial_Jornal_Por_Hora { get; set; }
        public Nullable<int> Tipo_Asalariado_Id { get; set; }
    
        public virtual Tipo_Asalariado Tipo_Asalariado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado_Honorario> Empleado_Honorario { get; set; }
    }
}
