//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalEnunciadoD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuracion_Salarial> Configuracion_Salarial { get; set; }
        public virtual DbSet<Dia_Trabajado> Dia_Trabajado { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empleado_Horario> Empleado_Horario { get; set; }
        public virtual DbSet<Tipo_Asalariado> Tipo_Asalariado { get; set; }
        public virtual DbSet<Empleado_Honorario> Empleado_Honorario { get; set; }
    }
}
