//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalEnunciadoD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia_Trabajado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dia_Trabajado()
        {
            this.Empleado_Horario = new HashSet<Empleado_Horario>();
        }
    
        public int Dia_Tabrajado_Id { get; set; }
        public string Dia_Trabajado_Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado_Horario> Empleado_Horario { get; set; }
    }
}
