//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalEnunciadoD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_Horario
    {
        public int Empleado_Horario_Id { get; set; }
        public Nullable<int> Empleado_Id { get; set; }
        public Nullable<int> Dia_Trabajado_Id { get; set; }
        public Nullable<decimal> Empleado_Horario_Trabajado_Diario { get; set; }
        public Nullable<decimal> Empleado_Horario_Trabajado_Semanal { get; set; }
        public Nullable<decimal> Empleado_Horario_Hora_Extra_100 { get; set; }
        public Nullable<decimal> Empleado_Horario_Hora_Extra_50 { get; set; }
        public Nullable<bool> Ausente_S_N { get; set; }
    
        public virtual Dia_Trabajado Dia_Trabajado { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
