//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalEnunciadoD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_Honorario
    {
        public int Empleado_Honorario_Id { get; set; }
        public int Empleado_Id { get; set; }
        public Nullable<int> Configuracion_Salarial_Id { get; set; }
    
        public virtual Configuracion_Salarial Configuracion_Salarial { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
