//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalEnunciadoD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Asalariado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Asalariado()
        {
            this.Configuracion_Salarial = new HashSet<Configuracion_Salarial>();
        }
    
        public int Tipo_Asalariado_Id { get; set; }
        public string Tipo_Asalariado_Codigo { get; set; }
        public string Tipo_Asalariado_Nombre { get; set; }
        public string Tipo_Asalariado_Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuracion_Salarial> Configuracion_Salarial { get; set; }
    }
}
